# Copyright (c) 2023 Files Community
# Licensed under the MIT License. See the LICENSE.

# Abstract:
#   This CI is triggered when a commit was added in the main branch directly or
#   a commit was added in a PR whose base branch is the main branch within this repository.

name: Files CI

on:
  pull_request:
    paths-ignore:
      - 'specs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'Files CI PR' || 'Files CI Validation' }}

env:
  WORKING_DIR: ${{ github.workspace }} # Default: 'D:\a\Files\Files'
  SOLUTION_PATH: '${{ github.workspace }}\Files.sln'
  PACKAGE_PROJECT_DIR: '${{ github.workspace }}\src\Files.App (Package)'
  PACKAGE_PROJECT_PATH: '${{ github.workspace }}\src\Files.App (Package)\Files.Package.wapproj'
  AUTOMATED_TESTS_ARCHITECTURE: 'x64'
  AUTOMATED_TESTS_CONFIGURATION: 'Release'
  AUTOMATED_TESTS_PROJECT_DIR: '${{ github.workspace }}\tests\Files.InteractionTests'
  AUTOMATED_TESTS_PROJECT_PATH: '${{ github.workspace }}\tests\Files.InteractionTests\Files.InteractionTests.csproj'
  AUTOMATED_TESTS_ASSEMBLY_DIR: '${{ github.workspace }}\artifacts\TestsAssembly'
  ARTIFACTS_STAGING_DIR:  '${{ github.workspace }}\artifacts'
  APPX_PACKAGE_DIR: '${{ github.workspace }}\artifacts\AppxPackages'
  APPX_SELFSIGNED_CERT_PATH: '${{ github.workspace }}\builds\Files_SelfSigned.pfx'

jobs:
  test:
    runs-on: windows-latest

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: TRX to MD
      shell: pwsh
      run: |
        $stringBuilder = New-Object System.Text.StringBuilder

        $mdPath = "testResults.md"
        [string]$title = "## Files Tests Result <img alt=""logo"" src=""https://github.com/files-community/Files/assets/62196528/6d4b489a-12be-4819-9bbc-a5f95858e77d"" width=""28"" align=""top"" />"

        [xml]$xmlDoc = Get-Content "testResults.trx"

        [void]$sb.AppendLine($title);
        [void]$sb.AppendLine();
        [void]$sb.AppendLine();
        [void]$sb.AppendLine();

        Write-Output $sb.ToString();
