name: Bump up Files version
run-name: Bump up Files version to ${{ inputs.files_new_version }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            files_new_version:
                required: true

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Fetch resources
              run: |
                  sed -i "s/<Identity Name=\".*\" Publisher=\".*\" Version=\".*\" \/>/<Identity Name="$1" Publisher="$2" Version="${{ inputs.files_new_version }}" \/>/g" "Package.appxmanifest"
            - name: Commit and push changes
              run: |
                git config --global user.name "onein528"
                git config --global user.email "onein528@outlook.com"
                git add -A
                git commit -m "Update Package.appxmanifest"
                git push origin HEAD:new-branch

