name: Bump up Files version
run-name: Bump up Files version to ${{ inputs.files_new_version }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            files_new_version:
                required: true

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Fetch resources
              run: |
                if [[ $search != "<Identity Name=\".*\" Publisher=\".*\" Version=\".*\" \/>" && $replace != "<Identity Name="$1" Publisher="$2" Version="${{ inputs.files_new_version }}" \/>" ]]; then
                  sed -i "s/$search/$replace/" "Package.appxmanifest"
                fi
            - name: Commit and push changes
              run: |
                git config --global user.name "your username"
                git config --global user.email "your email"
                git add -A
                git commit -m "commit message"
                git push

