name: Bump up Files version
run-name: Bump up Files version to ${{ inputs.files_new_version }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            files_new_version:
                required: true

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: ./scripts/fetch-resources.sh

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: Package.appxmanifest
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
