name: Bump up Files version
run-name: Bump up Files version to ${{ inputs.files_new_version }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            files_new_version:
                required: true

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update Package.appxmanifest
              run: |
                  sed -i "s/<Identity Name=\"\(.*\)\" Publisher=\"\(.*\)\" Version=\"\(.*\)\" \/>/<Identity Name=\"\1\" Publisher=\"\2\" Version=\"${{ inputs.files_new_version }}\" \/>/g" "Package.appxmanifest"
            - name: Create a new PR
              uses: peter-evans/create-pull-request@v4
              with:
                token: ${{ secrets.ACCESS_TOKEN }}
                commit-message: 'Package: Bump Files to ${{ inputs.files_new_version }}'
                committer: onein528 <onein528@outlook.com>
                author: onein528 <onein528@outlook.com>
                signoff: false
                branch: onein528/bump-up-to-${{ inputs.files_new_version }}
                delete-branch: true
                title: 'Package: Bump Files to ${{ inputs.files_new_version }}'
                body: |
                    body here
                labels: |
                    automation
                reviewers: onein528
                draft: false
