name: Files Package Version Bump Up
run-name: Bump up package version to ${{ inputs.files_new_version }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            files_new_version:
                description: 'New Version:'
                required: true

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update Package.appxmanifest
              run: |
                  sed -i "s/<Identity Name=\"\(.*\)\" Publisher=\"\(.*\)\" Version=\"\(.*\)\" \/>/<Identity Name=\"\1\" Publisher=\"\2\" Version=\"${{ inputs.files_new_version }}\" \/>/g" "Package.appxmanifest"
            - name: Create a new PR
              uses: peter-evans/create-pull-request@v4
              with:
                token: ${{ secrets.ACCESS_TOKEN }}
                commit-message: 'Package: Bump up Files package to ${{ inputs.files_new_version }}'
                committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                branch: 'release/${{ inputs.files_new_version }}'
                delete-branch: true
                title: 'Release: ${{ inputs.files_new_version }}'
                body: |
                    Bumps Files to ${{ inputs.files_new_version }}
                draft: false
